repos:

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args: [--fix]
      # - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: debug-statements
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict

  - repo: local
    hooks:
    - id: pylint
      name: pylint
      # entry: pylint mlutil/ -d C,R
      entry: pylint apipe/ -E
      language: python
      'types': [python]
      pass_filenames: false
      stages: [commit]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: python
        'types': [python]
        pass_filenames: false
        stages: [commit]

  - repo: local
    hooks:
      - id: poetry_export
        name: poetry_export
        entry: poetry export --without-hashes -o requirements.txt
        language: system
        pass_filenames: false