repos:

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: debug-statements
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict

  - repo: local
    hooks:
    - id: pylint
      name: pylint
      # entry: pylint mlutil/ -d C,R
      entry: pylint apipe/ -E
      language: python
      'types': [python]
      pass_filenames: false
      stages: [commit]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: python
        'types': [python]
        pass_filenames: false
        stages: [commit]
