name: Build Python Package

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - README.md

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[nobuild]')"
    runs-on: ubuntu-latest
    name: Build and Test
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: |
        pip install poetry
    - name: Install dependencies using poetry
      run: |
        poetry install
    - name: Check code formatting with black
      run: |
        poetry run black . --check
    - name: Check code with ruff
      run: |
        poetry run ruff check .
    - name: Build python package
      run: |
        echo "Build package"
        poetry build
    - name: Run testsuite
      run: |
        poetry run pytest -vv
