name: Publish Python Package

on:
  release:
    types:
      - created

jobs:
  publish:
    if: github.event_name == 'release'
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Set up python (required to determine version from git ref/hash)
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry --version
    - name: Build and publish on PyPI
      run: |
        git describe --tags --abbrev=0
        poetry version $(git describe --tags --abbrev=0)
        poetry build
        poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
